# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6048121419c0eac4b8bd8a178bcfe56bef59908fcac33ee806e72a5117492b9b23e133528852499aa5281e9c73796c6dc926fe9e9afc5eb10273a5ee587a4bb

test:
  secret_key_base: 68346cb4e30070d67d93acf700f7ac65b319be62fab564ee0660c63d159a6ec767259288e066eee842d2389c0244525d611663762c671b310d2189495dc91d84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
